MUMPS.NET for Dummies~Format=5.S~
14 Jun 2013  10:02 PM   Cache
^ADS("ID",1)
486SX Computer¥COMPUTERS¥8MB RAM, 500MB HD, Monitor, Printer¥£700.00¥317-884-3233¥billhatfield@worldnet.att.net¥IN¥pickle¥1/11/1999 00:00:00
^ADS("ID",2)
86 Pinto¥VEHICLES¥Low milage, new brakes, regular maintenance¥£5000.02¥317-344-2244¥vred@aol.com¥USA¥¥5/11/1999 00:00:00
^ADS("ID",3)
95 Ford Escort¥VEHICLES¥Like new¥£17000.00¥432-322-4433¥ico@vreet.com¥UK¥¥2/11/1999 00:00:00
^ADS("ID",4)
Pentium II¥COMPUTERS¥64MB RAM, 7GB HD, 4MB Video RAM¥£3000.00¥442-133-4322¥whet@teepee.com¥OH¥pickle¥7/11/1999 00:00:00
^ADS("ID",5)
93 Plymouth Duster¥VEHICLES¥Ugly, but it runs¥£4500.00¥322-432-1344¥ted@aol.com¥IL¥pickle¥1/11/1999 00:00:00
^ADS("ID",7)
Macintosh Performa 450¥COMPUTERS¥Fair condition, Claris works 2.0, games, screensaver & keyboard. Monitor included.¥£651.00¥378-433-3244¥gabef@aol.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",8)
US Robotics 28.8 Modem¥COMPUTERS¥Will sell or trade¥£100.00¥433-223-4321¥modemman@aol.com¥IN¥pickle¥21/11/1999 00:00:00
^ADS("ID",9)
Powerbook 14000¥COMPUTERS¥64 MB RAM, 3.5" floppy, 6x CD-ROM, dot matrix color printer, software, 33.6 modem.¥£2500.00¥884-234-8833¥cam@fifred.com¥CA¥pickle¥21/11/1999 00:00:00
^ADS("ID",10)
Packard Bell PB5330 Computer¥COMPUTERS¥Like new, with Cannon color bubble jet printer.¥£1400.00¥432-334-8822¥bjkatz@fifo.com¥IL¥pickle¥21/11/1999 00:00:00
^ADS("ID",11)
Compaq Presario 1065 Laptop¥COMPUTERS¥16MB RAM, 1GB HD, 11.3" screen, 6x CD-ROM, 33.6 fax modem, case.¥£1300.00¥432-123-6693¥kiko@fizz.com¥WI¥pickle¥21/11/1999 00:00:00
^ADS("ID",12)
486DX66¥COMPUTERS¥8MB RAM, 495MB HD, 3.5"/5.25" floppies, modem, Windows 3.1, MS Works.¥£350.00¥332-134-1446¥atiko@fifi.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",13)
Pentium 200¥COMPUTERS¥2.5GB HD, 16MB RAM, 33.6 modem, 16x CD-ROM, 32-bit wave-table sound card, 64-bit video card with 2MB RAM, Windows 95.¥£995.00¥322-443-2235¥wastenot@willy.com¥AL¥pickle¥21/11/1999 00:00:00
^ADS("ID",14)
94 Star Trek Ornament: Klingon Bird of Prey¥COLLECTABLES¥Excellent condition, includes original box.¥£15.00¥343-222-5533¥echo@will.com¥TX¥pickle¥21/11/1999 00:00:00
^ADS("ID",15)
McDonald's Beanie Babies¥COLLECTIBLES¥10 pieces, new in bags with Happy Meal bag checklist.¥£90.00¥322-468-9983¥benie@baby.com¥IL¥pickle¥21/11/1999 00:00:00
^ADS("ID",16)
13 Disney Beanies¥COLLECTIBLES¥Complete set. Great Christmas gift. Piglet, Eore, Pooh, Sebastain, Flounder, Mickey, Minnie, Grumpy, Tigger, Goofy, Pluto, Dopey and Dalmation.
^ADS("ID",17)
80s Comic Books¥COLLECTIBLES¥Many good titles, near mint condition, serious calls only.¥153.00¥322-486-6883¥waca@edgequest.com¥OH¥¥21/11/1999 00:00:00
^ADS("ID",18)
Magic Card Collection¥COLLECTIBLES¥Over 4500 rare, uncommon and common. Alpha through Mirage.¥£600.00¥844-486-8833¥piko@finfi.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",19)
Michael Jordan Rookie Card¥COLLECTIBLES¥Complete set with stickers. Mint condition.¥£1200.00¥344-386-9933¥mjmj@fifi.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",20)
Baby Grand Piano¥GENERAL¥Excellent condition. 4 years old. Ebony polish. Tuned every 6 months. Must sell.¥4900.00¥344-388-9283¥perry@williamson.com¥IL¥pickle¥21/11/1999 00:00:00
^ADS("ID",21)
Casio Electronic Keyboard¥GENERAL¥62 tones and rhythms. Hardly used.¥£175.00¥995-330-9845¥faith@kim.com¥TX¥¥21/11/1999 00:00:00
^ADS("ID",22)
Men's Brunswick Bowling Ball¥GENERAL¥16lb ball and leather bag¥£20.00¥553-329-9938¥tomv@well.com¥MA¥pickle¥21/11/1999 00:00:00
^ADS("ID",23)
Mitsubishi golf clubs¥GENERAL¥2 years old. Like new. 3-PW, 1, 3 & 5 woods, steel shaft, over-sized heads. Excellent condition.¥£130.00¥834-993-9922¥bobbyh@kato.com¥FL¥pickle¥21/11/1999 00:00:00
^ADS("ID",24)
88 Ford Mustang LX Coupe¥VEHICLES¥2.3 5 speed. Blue on blue, aluminum wheels. Runs and drives excellent.¥£1801.00¥385-903-9933¥bradk@fellow.com¥OK¥¥21/11/1999 00:00:00
^ADS("ID",25)
95 Ford Taurus GL¥VEHICLES¥Keyless entry. Loaded. PDL PW CC ABS TW AC. Dual air bags. 37000 miles. Extended warrenty.
^ADS("ID",26)
87 Dodge 600¥VEHICLES¥4-door, 46000 miles, Like new tires. Air, power stearing, power breaks, AM/FM stereo.¥3056.00¥338-827-7833¥wallyB@pigs.org¥IN¥pickle¥21/11/1999 00:00:00
^ADS("ID",27)
87 Saab 900¥VEHICLES¥Needs some work¥£830.00¥883-254-8982¥Barrym@christo.com¥IN¥pickle¥21/11/1999 00:00:00
^ADS("ID",28)
2 BR Home¥REALESTATE¥Great condition, new roof, fensed yard, quiet neighborhood.¥£37000.00¥332-388-9978¥fits@filly.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",29)
4 BR home¥REALESTATE¥2 bath, large eat-in kitchen, FR, large LR with oak flooring. 3 car garage. Large wooded lot with creek.¥£73000.00¥322-883-8279¥tally@wiggam.org¥IL¥¥21/11/1999 00:00:00
^ADS("ID",30)
Mobile Home in Witcome Estates¥REALESTATE¥3 BR, 1 bath, fireplace, large corner lot, small barn. Appliances stay. Must sell soon.
^ADS("ID",31)
2 BR 2 bath mobile home¥REALESTATE¥Covered entry. 8x12 shed and a lot of extras. 3 years old. Near downtown.¥£23500.00¥322-887-3822¥Mikelaf@feller.com¥FL¥pickle¥21/11/1999 00:00:00
^ADS("ID",32)
97 Mobile Home¥REALESTATE¥2 BR 16x50 mobile home. Appliances stay. For sale on contract.¥£25000.00¥322-482-8902¥billk@farm.com¥IA¥pickle¥21/11/1999 00:00:00
^ADS("ID",33)
Cedar Log Cabin¥REALESTATE¥4 BR, 2 bath, 2200 square feet on 3 acres. Lake. 40 miles east of downtown.¥£170000.00¥382-993-2882¥chester@outthere.com¥OH¥pickle¥21/11/1999 00:00:00
^ADS("ID",43)
93 Chevy Suburban¥VEHICLES¥4-wheel drive, White with blue interior. Rear AC. Extra clean. 85000 miles.¥£17900.50¥328-932-8377¥RickV@willow.org¥IL¥¥23/11/1999 00:00:00
^ADS("ID",44)
Pentium 200¥COMPUTERS¥64MB RAM, 5GB HD, 21" NEC Monitor, 12x CD-ROM Drive.¥£2000.00¥358-882-9933¥bha@aol.com¥IN¥pickle¥3/12/1999 00:00:00
^ADS("ID",45)
Pentium 166¥COMPUTERS¥3GB HD, 32MB RAM, 17" monitor.¥£1700.00¥557-993-8288¥ratty@aol.com¥OH¥pickle¥3/12/1999 00:00:00
^ADS("ID",46)
Pentium III 550¥COMPUTERS¥Hot, hot, hot! 256MB RAM, 30GB Hard drive, 21" NEC MultiSync monitor¥£1895.00¥433-555-4444¥fred@abl.com¥IN¥pickle¥16/12/1999 00:00:00
^ADS("ID",47)
2004 Vauxhall Zafira¥VEHICLES¥Good condition, warning light appears every now and again!¥1,599¥0113¥psimon1@supanet.com¥WY¥a¥28/05/2013 00:00:00


